### ISSUE TITLE
"looks_like_sequence" function improvement

### ISSUE THREAD

**Issue by chaza150** [thruston/python-tabulate#1]
### Proposed change to "looks_like_sequence" function in tabulate.py

This change checks for a guaranteed arithmetic progression.
Another option would be to check neighbours for A < B < C < D etc. for a looser definition.

``` python
def looks_like_sequence(numbers):
    '''Do these decimals appear to be a list of years, or some other numeric labels?
    We are trying to see if they are in arithmetic progression... (sort of)
    >>> looks_like_sequence((1,2,3))
    True
    >>> looks_like_sequence((1990, 1980, 1970))
    True
    >>> looks_like_sequence((3.14, 2.718, 6.28))
    False
    >>> looks_like_sequence((28, 44, 20, 0))
    False
    '''

    # Edge cases: One element is always progression. False if 0 appears in sequence. (Change as needed)
    if len(numbers) < 2 :
        return True
    elif 0 in numbers :
        return False

    seq = sorted(numbers)
    ln = len(seq)
    diff = seq[1] - seq[0]

    # Checks arithmetic progression for sequences longer than 1 item
    return 2*ln*seq[0] + (ln * ln - ln)*diff == 2*sum(seq)

**Comment by chaza150** [comment]
@thruston 
Receiving this stacktrace when running this method:
```
Traceback (most recent call last):
  File "", line 252, in <module>
    t.do("sort abc rule add")
  File "tabulate.py", line 602, in do
    self.operations[op](' '.join(argument))
  File "tabulate.py", line 981, in _append_reduction
    if not any(booleans) or (c == 0 and looks_like_sequence(decimals)):
  File "tabulate.py", line 258, in looks_like_sequence
    delta = numbers[0] - numbers[1]
IndexError: list index out of range
```
More than likely caused by sequences of length < 2 being passed to `looks_like_sequence`. Please fix by adding check:
```python
n = len(numbers)
if n < 2:
    return True
delta = numbers[0] - numbers[1]
```

**Comment by thruston** [comment]
thanks for the report.   Fixed by trapping the exception.
